spring:
  application:
    name: platform
  profiles:
    active: '@activeProfile@'
  jmx:
    enabled: false
  freemarker:
    check-template-location: false
    cache: false
    charset: UTF-8
    template-loader-path: classpath:/templates/
    content-type: text/html
    suffix: .ftl
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    settings:
      number_format: 0.##
      template_exception_handler: ignore
      classic_compatible: true
      date_format: yyyy-MM-dd
      datetime_format: yyyy-MM-dd HH:mm:ss
  cache:
    redis:
      key-prefix: platform:tmp
      key-prefix-permanent: platform:per
  mail:
    host: smtp.exmail.qq.com
    username: kbzf_report@yacol.com
    password: 5tgb^YHN7ujm
    properties:
      mail:
        smtp:
          auth: true
          timeout: 25000
    port: 25

server:
  port: 9015

ftlPath: /email.ftl

#mybatis配置
mybatis:
  mapper-locations: classpath:sql_mapper/*.xml
  type-aliases-package: com.bazzi.job.platform.model
  configuration:
    call-setters-on-nulls: true

#通用mapper配置
mapper:
  mappers: com.bazzi.job.common.mybatis.BaseMapper
  not-empty: false
  identity: MYSQL

#PageHelper分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true

#logback日志
logging:
  config: classpath:logback-spring.xml
  charset: UTF-8
  file:
    path: /opt/logs/
